export const EVENTS = {
  ACCESS_TOKEN: 'accessToken',
  MEASUREMENT_MEAN_DATA: 'onMeasurementMeanData',
  MEASUREMENT_STATUS: 'onMeasurementStatus',
  SENDING_RATE_WARNING: 'onSendingRateWarning',
  MEASUREMENT_PROGRESS: 'onMeasurementProgress',
  MEASUREMENT_SIGNAL: 'onMeasurementSignal',
  MOVING_WARNING: 'onMovingWarning',
  BLOOD_PRESSURE: 'onBloodPressure',
  UNSTABLE_CONDITIONS_WARNING: 'onUnstableConditionsWarning',
  INTERFERENCE_WARNING: 'onInterferenceWarning',
  SIGNAL_QUALITY: 'onSignalQuality',
  HRV_METRICS: 'onHrvMetrics',
  STRESS_INDEX: 'onStressIndex',
  AFIB_RISK: 'onAfibRisk',
}
